/** Style: Aviation Operations Room — dark analytical instruments, route arcs, verified Aero Teal signals. */
import { useState, type ReactNode } from "react";
import { AlertTriangle, Bot, CheckCircle2, ChevronRight, CircleHelp, Database, FileCheck2, Gauge, MapPin, Plane, Plus, RefreshCw, ShieldCheck, Sparkles, X } from "lucide-react";
import { Area, AreaChart, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AUDIT_EVENTS, BOOKING_DATA, CPI_FACTORS, CPI_BUCKETS, TREND_DATA, WEIGHTS, formatCurrency, reliability, routeLabel, type RouteRecord } from "@/data/mockData";
import { useTheme } from "@/contexts/ThemeContext";

const severityClass = (severity: string) => severity === "High" ? "status-danger" : severity === "Medium" ? "status-warn" : "status-info";

export function CPICompatibilityScore({ score, compact = false, onClick }: { score: number; compact?: boolean; onClick?: () => void }) {
  const ringStyle = { background: `conic-gradient(#71879F ${score * 3.6}deg, rgba(255,255,255,.10) 0deg)` };
  return <button onClick={onClick} className={`group flex items-center gap-3 text-left ${onClick ? "cursor-pointer" : "cursor-default"}`} title={onClick ? "View score breakdown" : undefined}>
    <span className={`${compact ? "h-10 w-10" : "h-16 w-16"} relative grid shrink-0 place-items-center rounded-full p-[3px] transition-transform group-hover:scale-105`} style={ringStyle}><span className="grid h-full w-full place-items-center rounded-full bg-card text-xs font-bold text-foreground">{score}</span></span>
    <span className="min-w-0"><span className="data-label">CPI compatibility</span><span className={`${compact ? "text-xs" : "text-sm"} mt-0.5 block font-semibold text-foreground`}>{reliability(score)}</span></span>
  </button>;
}

export function CPICompatibilityBreakdown({ score = 96 }: { score?: number }) {
  return <div className="space-y-3"><div className="flex items-start justify-between gap-3"><div><p className="data-label">Statistical reliability</p><h3 className="mt-1 font-display text-xl font-semibold">CPI Compatibility Score: {score}/100</h3></div><span className="status-success">{reliability(score)}</span></div><div className="mt-5 space-y-2.5">{CPI_FACTORS.map((factor) => <div className="flex items-center justify-between gap-4 text-sm" key={factor.label}><span className="flex items-center gap-2 text-muted-foreground"><CheckCircle2 className="h-4 w-4 text-primary" />{factor.label}</span><strong className="font-mono text-foreground">{factor.score}/{factor.max}</strong></div>)}</div></div>;
}

export function AnomalyCard({ route, onSelect }: { route: RouteRecord; onSelect?: (route: RouteRecord) => void }) {
  return <button onClick={() => onSelect?.(route)} className="instrument-card group w-full text-left"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-[#ee7e65]" /><span className="data-label text-[#ee7e65]">Anomaly detected</span></div><h3 className="mt-2 font-display text-lg font-semibold">{routeLabel(route)}</h3></div><span className={severityClass(route.severity)}>{route.severity}</span></div><div className="mt-5 grid grid-cols-3 gap-3"><Metric label="Current" value={formatCurrency(route.currentFare)} /><Metric label="7D baseline" value={formatCurrency(route.baseline)} /><Metric label="Difference" value={`+${route.change.toFixed(0)}%`} color="text-[#ee7e65]" /></div><div className="mt-4 flex items-center justify-between border-t border-border/70 pt-3 text-xs text-muted-foreground"><span>Anomaly score {route.anomalyScore}/100</span><span className="flex items-center gap-1 text-primary">Investigate <ChevronRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" /></span></div></button>;
}

export function AnomalyDetailsModal({ route, onClose, onReview }: { route: RouteRecord | null; onClose: () => void; onReview: (status: string) => void }) {
  if (!route) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#07141d]/80 p-4 backdrop-blur-sm"><section className="surface-strong max-h-[88vh] w-full max-w-xl overflow-auto p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="data-label text-[#ee7e65]">Anomaly investigation</p><h2 className="mt-1 font-display text-2xl font-semibold">{routeLabel(route)}</h2></div><button onClick={onClose} className="icon-button" aria-label="Close anomaly details"><X className="h-4 w-4" /></button></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Current fare" value={formatCurrency(route.currentFare)} /><Metric label="Baseline" value={formatCurrency(route.baseline)} /><Metric label="Change" value={`+${route.change}%`} color="text-[#ee7e65]" /><Metric label="Anomaly score" value={`${route.anomalyScore}/100`} /></div><div className="mt-6 rounded-xl border border-[#ee7e65]/25 bg-[#ee7e65]/8 p-4"><p className="data-label text-[#ee7e65]">Possible explanation</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{route.explanation}</p></div><div className="mt-6"><CPICompatibilityScore score={route.score} compact /></div><div className="mt-6 grid gap-2 sm:grid-cols-3"><button onClick={() => onReview("Reviewed")} className="button-secondary">Mark reviewed</button><button onClick={() => onReview("Valid market movement")} className="button-secondary">Valid movement</button><button onClick={() => onReview("Possible data issue")} className="button-danger">Possible data issue</button></div></section></div>;
}

export function InflationHeatmap({ routes, onRouteSelect }: { routes: RouteRecord[]; onRouteSelect: (route: RouteRecord) => void }) {
  const visible = routes.filter((r) => ["DEL-BOM", "AMD-DEL", "BOM-BLR", "MAA-CCU", "HYD-BOM", "GOI-DEL"].includes(r.id));
  const points: Record<string, string> = { "DEL-BOM": "left-[42%] top-[23%]", "AMD-DEL": "left-[27%] top-[32%]", "BOM-BLR": "left-[33%] top-[60%]", "MAA-CCU": "left-[58%] top-[69%]", "HYD-BOM": "left-[48%] top-[53%]", "GOI-DEL": "left-[22%] top-[63%]" };
  return <div className="relative min-h-[420px] overflow-hidden rounded-2xl border border-border/80 bg-[radial-gradient(circle_at_46%_35%,rgba(95,224,207,.15),transparent_37%),linear-gradient(135deg,#102532,#0a1823)]"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.08)_1px,transparent_1px)] [background-size:28px_28px]" /><svg viewBox="0 0 300 390" className="absolute left-1/2 top-1/2 h-[105%] w-auto -translate-x-1/2 -translate-y-1/2 fill-[#274354]/80 stroke-[#5fe0cf]/30 stroke-[1.4]"><path d="M144 17l34 26 14 33 28 27-7 28 21 39-21 27 5 32-25 23-16 58-19 23-10 48-24-46-22-34 8-31-30-25 2-49-25-37 16-22-12-29 23-33 3-34 28-25 8-35z" /></svg><svg viewBox="0 0 100 100" className="absolute inset-0 h-full w-full overflow-visible"><path d="M41 25 C 30 38, 38 55, 32 61" fill="none" stroke="#5fe0cf" strokeDasharray="3 3" strokeWidth=".5" opacity=".65" /><path d="M42 25 C 50 44, 35 50, 48 54" fill="none" stroke="#ee7e65" strokeDasharray="3 3" strokeWidth=".5" opacity=".75" /><path d="M33 61 C 45 66, 54 67, 59 70" fill="none" stroke="#7fa8ff" strokeDasharray="3 3" strokeWidth=".5" opacity=".6" /></svg>{visible.map((route) => <button key={route.id} onClick={() => onRouteSelect(route)} className={`heatpoint ${points[route.id] || "left-1/2 top-1/2"}`}><span className={route.change > 10 ? "heatpoint-dot high" : route.change < 0 ? "heatpoint-dot low" : "heatpoint-dot"} /><span className="heatpoint-label"><strong>{route.origin} → {route.destination}</strong><em className={route.change >= 0 ? "text-[#eea06c]" : "text-primary"}>{route.change >= 0 ? "+" : ""}{route.change.toFixed(0)}%</em></span></button>)}<div className="absolute bottom-5 left-5 rounded-lg border border-white/10 bg-[#0c1d28]/90 px-3 py-2 text-xs text-slate-300 backdrop-blur"><span className="mr-3 text-primary">● decrease</span><span className="text-[#eea06c]">● increase</span></div></div>;
}

export function PriceExplanationPanel({ route }: { route: RouteRecord }) {
  const factors = [
    ["Travel date approaching", "High impact", "92%", "The departure window is within seven days, a period historically associated with consistent fare increases."],
    ["Weekend demand", "High impact", "88%", "The relevant travel date falls inside an observed high-demand weekend pattern."],
    ["Cross-source price agreement", "Strong signal", "94%", `${route.sources.length} monitored sources show directionally similar movement.`],
    ["Historical route volatility", "Moderate impact", "76%", "Movement is evaluated against the route’s established historical variation band."],
  ];
  return <div><div className="flex items-end justify-between"><div><p className="data-label">Explainable price change engine</p><h3 className="mt-1 font-display text-xl font-semibold">Why did the price move?</h3></div><span className={route.change >= 0 ? "text-xl font-bold text-[#eea06c]" : "text-xl font-bold text-primary"}>{route.change >= 0 ? "+" : ""}{route.change.toFixed(1)}%</span></div><div className="mt-5 space-y-3">{factors.map(([title, impact, confidence, description]) => <div className="rounded-xl border border-border/75 bg-secondary/25 p-4" key={title}><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{title}</strong><span className="text-xs font-semibold text-primary">{impact} · {confidence}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div>)}</div></div>;
}

export function BookingWindowChart({ route }: { route: RouteRecord }) {
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="data-label">Booking window analysis</p><h3 className="mt-1 font-display text-xl font-semibold">{routeLabel(route)} · 25 September 2026</h3></div><span className="status-success">CPI comparison window: 14–21 days</span></div><div className="mt-5 h-[245px] w-full"><ResponsiveContainer><AreaChart data={BOOKING_DATA} margin={{ left: -10, right: 8, top: 6 }}><defs><linearGradient id="fareArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#6A9893" stopOpacity={.32}/><stop offset="100%" stopColor="#6A9893" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="days" axisLine={false} tickLine={false} tick={{ fill: "#8497a3", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#8497a3", fontSize: 11 }} tickFormatter={(v) => `₹${v/1000}k`} /><Tooltip contentStyle={{ background: "#1A2330", border: "1px solid rgba(143,160,179,.24)", borderRadius: 10 }} formatter={(v: number) => [formatCurrency(v), "Average fare"]} /><Area type="monotone" dataKey="fare" stroke="#6A9893" strokeWidth={2.5} fill="url(#fareArea)" /></AreaChart></ResponsiveContainer></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Fare inflation" value="+148%" /><Metric label="Cheapest window" value="30 days" /><Metric label="High-risk window" value="3–7 days" color="text-[#a48662]" /></div></div>;
}

export function SyntheticBasketCard({ routes }: { routes: RouteRecord[] }) {
  const included = routes.filter((route) => route.included);
  return <div><p className="data-label">India synthetic airfare basket</p><h3 className="mt-1 font-display text-xl font-semibold">Route representation you can trace</h3><div className="mt-5 space-y-3">{["Tier 1", "Tier 2", "Tier 3"].map((tier) => { const items = included.filter((route) => route.tier === tier); const total = items.reduce((sum, route) => sum + route.weight, 0); return <div key={tier} className="rounded-xl border border-border/75 bg-secondary/25 p-4"><div className="flex justify-between"><strong className="text-sm">{tier} routes</strong><span className="text-xs text-primary">Weight: {total || (tier === "Tier 1" ? 55 : tier === "Tier 2" ? 30 : 15)}%</span></div><p className="mt-2 text-sm text-muted-foreground">{items.length ? items.slice(0, 4).map(routeLabel).join(" · ") : "Regional and emerging route candidates"}</p></div> })}</div></div>;
}

export function BasketWeightChart() {
  return <div className="relative h-[250px]"><ResponsiveContainer><PieChart><Pie data={WEIGHTS} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={5}>{WEIGHTS.map((entry) => <Cell key={entry.name} fill={entry.fill} />)}</Pie><Tooltip contentStyle={{ background: "#102532", border: "1px solid rgba(255,255,255,.12)", borderRadius: 10 }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><span className="data-label leading-4">NATIONAL<br/>BASKET</span></div></div>;
}

export function IndexComparator() {
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="data-label">Illustrative comparison</p><h3 className="mt-1 font-display text-xl font-semibold">Real-time vs reference index</h3></div><span className="status-warn">Prototype demonstration</span></div><div className="mt-5 grid gap-3 md:grid-cols-3"><Metric label="AeroIndex real-time" value="118.4" sub="▲ +3.2%" /><Metric label="Reference index" value="114.2" sub="▲ +1.8%" /><Metric label="Difference" value="+3.7%" color="text-primary" sub="early-signal spread" /></div><p className="mt-5 border-l-2 border-primary pl-4 text-sm leading-6 text-muted-foreground">High-frequency airfare data can provide early signals and complement traditional price measurement approaches. <span className="text-foreground">Not an official published CPI value.</span></p></div>;
}

export function FareAuditTimeline() {
  return <div><p className="data-label">Observation audit trail</p><h3 className="mt-1 font-display text-xl font-semibold">DEL → BOM fare observation</h3><div className="mt-5 divide-y divide-border/60 border-l border-primary/40 pl-5">{AUDIT_EVENTS.map((event) => <div className="relative py-4" key={event.time}><span className="absolute -left-[25px] top-[22px] h-2 w-2 rounded-full bg-primary shadow-[0_0_0_4px_rgba(95,224,207,.12)]" /><div className="flex flex-wrap items-baseline justify-between gap-2"><strong className="text-sm">{event.title}</strong><span className="font-mono text-xs text-primary">{event.time}</span></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{event.detail}</p></div>)}</div></div>;
}

export function RouteRecommendationCard({ route, onAdd }: { route: RouteRecord; onAdd: () => void }) {
  return <div><div className="flex items-start justify-between gap-4"><div><p className="data-label">Recommended for airfare basket</p><h3 className="mt-1 font-display text-xl font-semibold">{routeLabel(route)}</h3></div><CPICompatibilityScore score={route.score} compact /></div><div className="mt-6 grid grid-cols-3 gap-3"><Metric label="Recommendation" value={`${route.recommendation}/100`} /><Metric label="Traffic" value={route.traffic} /><Metric label="Availability" value={`${route.availability}%`} /></div><p className="mt-5 text-sm leading-6 text-muted-foreground"><span className="text-primary">✓</span> Strong regional representation &nbsp; <span className="text-primary">✓</span> Reliable historical observations &nbsp; <span className="text-primary">✓</span> High data availability</p><button onClick={onAdd} className="button-primary mt-5"><Plus className="h-4 w-4" />Add to basket</button></div>;
}

export function RouteSelectionTable({ routes, onToggle }: { routes: RouteRecord[]; onToggle: (route: RouteRecord) => void }) {
  return <div className="overflow-x-auto"><table className="data-table min-w-[700px]"><thead><tr><th>Route</th><th>Recommendation</th><th>Traffic</th><th>Data quality</th><th>Status</th><th /></tr></thead><tbody>{[...routes].sort((a,b) => b.recommendation-a.recommendation).slice(0,8).map((route) => <tr key={route.id}><td><strong>{routeLabel(route)}</strong></td><td><span className="font-mono text-primary">{route.recommendation}/100</span></td><td>{route.traffic}</td><td>{route.score >= 90 ? "Excellent" : route.score >= 75 ? "Good" : "Review"}</td><td><span className={route.included ? "status-success" : "status-info"}>{route.included ? "Included" : "Candidate"}</span></td><td><button onClick={() => onToggle(route)} className="table-action">{route.included ? "Remove" : "Add"}</button></td></tr>)}</tbody></table></div>;
}

export function AeroInsightPanel({ open, onClose, route }: { open: boolean; onClose: () => void; route: RouteRecord }) {
  const [question, setQuestion] = useState("Why did prices increase?");
  const responses: Record<string, string> = { "Why did prices increase?": `${routeLabel(route)} moved ${route.change >= 0 ? "up" : "down"} ${Math.abs(route.change).toFixed(1)}%. ${route.explanation}`, "Show highest anomaly.": "AMD → DEL has the highest active anomaly score at 92/100, driven by a 42% gap against its seven-day baseline.", "Which routes are most volatile?": "AMD → DEL, BOM → GOI and DEL → BOM currently show the strongest variance against their recent route baselines.", "How is the national index calculated?": "Route prices are standardized, aggregated into route-level Jevons indices, weighted by the synthetic basket, then combined using Törnqvist aggregation.", "Show this week’s biggest changes.": "AMD → DEL leads weekly increases at +42.0%, followed by BOM → GOI at +12.8% and DEL → BOM at +12.0%." };
  return <aside className={`aeroinsight-panel ${open ? "translate-x-0" : "translate-x-[110%]"}`}><div className="flex items-start justify-between"><div><span className="flex items-center gap-2 text-xs font-bold tracking-[.16em] text-primary"><Bot className="h-4 w-4" />AEROINSIGHT</span><h3 className="mt-2 font-display text-xl font-semibold">Analytical assistant</h3></div><button onClick={onClose} className="icon-button"><X className="h-4 w-4" /></button></div><div className="mt-6 rounded-xl border border-primary/20 bg-primary/8 p-4"><p className="data-label text-primary">Current analysis</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{responses[question]}</p><p className="mt-4 text-xs font-semibold text-primary">Confidence: 91%</p></div><div className="mt-6"><p className="data-label">Ask a quick question</p><div className="mt-3 flex flex-wrap gap-2">{Object.keys(responses).map((item) => <QuickQuestionButton key={item} active={question === item} onClick={() => setQuestion(item)}>{item}</QuickQuestionButton>)}</div></div><div className="mt-auto border-t border-border/70 pt-5 text-xs leading-5 text-muted-foreground">Deterministic demonstration engine · ready to exchange for a governed AI service.</div></aside>;
}

export function AIInsightCard({ onOpen }: { onOpen: () => void }) {
  return <button onClick={onOpen} className="relative overflow-hidden rounded-2xl border border-primary/25 bg-[linear-gradient(135deg,rgba(95,224,207,.16),rgba(17,37,49,.85))] p-5 text-left transition hover:-translate-y-0.5"><Sparkles className="absolute right-4 top-4 h-16 w-16 text-primary/10" /><div className="relative"><span className="flex items-center gap-2 text-xs font-bold tracking-[.16em] text-primary"><Bot className="h-4 w-4" />AEROINSIGHT</span><p className="mt-4 font-display text-xl font-semibold leading-7">“Airfare inflation accelerated by 2.1% this week.”</p><p className="mt-3 text-sm text-muted-foreground">Primary drivers: weekend demand · booking-window compression · cross-source agreement</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-primary">View full analysis <ChevronRight className="h-4 w-4" /></span></div></button>;
}

export function QuickQuestionButton({ children, active, onClick }: { children: ReactNode; active?: boolean; onClick: () => void }) {
  return <button onClick={onClick} className={`rounded-lg border px-3 py-2 text-left text-xs transition ${active ? "border-primary/60 bg-primary/15 text-primary" : "border-border bg-secondary/40 text-muted-foreground hover:border-primary/30 hover:text-foreground"}`}>{children}</button>;
}

export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme();
  const dark = theme === "dark";
  return <button className="theme-toggle" onClick={toggleTheme} title={`Switch to ${dark ? "Executive Light" : "Dark"} mode`}><span className="grid h-6 w-6 place-items-center rounded-full bg-primary text-[#09202a]">{dark ? "☾" : "☀"}</span><span className="hidden text-xs font-semibold sm:block">{dark ? "Dark" : "Executive Light"}</span></button>;
}

export function NationalIndexTrend() {
  return <div className="h-[285px] w-full"><ResponsiveContainer><LineChart data={TREND_DATA} margin={{ left: -18, right: 8, top: 10 }}><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#8497a3", fontSize: 11 }} /><YAxis domain={[108, 120]} axisLine={false} tickLine={false} tick={{ fill: "#8497a3", fontSize: 11 }} /><Tooltip contentStyle={{ background: "#1A2330", border: "1px solid rgba(143,160,179,.24)", borderRadius: 10 }} /><Line type="monotone" dataKey="index" name="AeroIndex" stroke="#6A9893" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="reference" name="Reference" stroke="#A48662" strokeDasharray="5 4" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div>;
}

export function CPIBucketChart() {
  return <div className="relative h-[240px]"><ResponsiveContainer><PieChart><Pie data={CPI_BUCKETS} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={4}>{CPI_BUCKETS.map((item) => <Cell key={item.name} fill={item.fill} />)}</Pie><Tooltip contentStyle={{ background: "#102532", border: "1px solid rgba(255,255,255,.12)", borderRadius: 10 }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><span className="text-center text-xs font-semibold text-muted-foreground">CPI<br/>DISTRIBUTION</span></div></div>;
}

export function PipelineStatus({ running, onRun }: { running: boolean; onRun?: () => void }) {
  const stages = ["Playwright", "Validation", "Normalization", "PostgreSQL", "Index Engine", "Anomaly Detection", "FastAPI", "Dashboard"];
  return <div><div className="flex items-center justify-between"><div><p className="data-label">Data pipeline</p><h3 className="mt-1 font-display text-xl font-semibold">Collection to signal</h3></div>{onRun && <button onClick={onRun} className="button-primary text-xs">{running ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}{running ? "Ingesting" : "Run ingestion"}</button>}</div><div className="mt-6 flex flex-wrap items-center gap-2">{stages.map((stage, i) => <div className="flex items-center gap-2" key={stage}><span className={`rounded-lg border px-2.5 py-2 text-xs font-medium ${running && i < 4 ? "border-primary/40 bg-primary/10 text-primary" : "border-border bg-secondary/30 text-muted-foreground"}`}>{i === 0 && <Database className="mr-1.5 inline h-3.5 w-3.5" />}{stage}</span>{i < stages.length - 1 && <ChevronRight className="h-3.5 w-3.5 text-muted-foreground/60" />}</div>)}</div><p className="mt-5 text-sm text-muted-foreground"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-primary shadow-[0_0_12px_#5FE0CF]" />{running ? "Run AIX-2481 is validating source observations." : "All monitored source jobs completed on schedule."}</p></div>;
}

function Metric({ label, value, sub, color = "" }: { label: string; value: string; sub?: string; color?: string }) {
  return <div><p className="data-label">{label}</p><p className={`mt-1 truncate font-display text-lg font-semibold ${color}`}>{value}</p>{sub && <p className="mt-0.5 text-xs text-muted-foreground">{sub}</p>}</div>;
}

export const Icons = { AlertTriangle, Bot, CircleHelp, FileCheck2, Gauge, MapPin, Plane, ShieldCheck };
