/** Style: Aviation Operations Room — a compact executive presentation board for the institutional airspace design system. */
import { useLocation } from "wouter";
import { Accessibility, ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, Database, Keyboard, ShieldCheck } from "lucide-react";
import { Brand } from "@/components/Brand";
import { ThemeToggle } from "@/components/analytics";
import { AmbientMotionControl } from "@/components/AmbientMotionControl";
import { useMotion } from "@/contexts/MotionContext";

const colors = [
  { name: "Graphite Navy", hex: "#111923", use: "Primary field and command canvas", color: "#111923" },
  { name: "Steel Signal", hex: "#536F8C", use: "Navigation and primary controls", color: "#536F8C" },
  { name: "Verification Teal", hex: "#6A9893", use: "Live and verified analytical signal", color: "#6A9893" },
  { name: "Sage Success", hex: "#6F8A75", use: "Healthy, passed, and eligible states", color: "#6F8A75" },
  { name: "Antique Bronze", hex: "#A48662", use: "Reference series and caution", color: "#A48662" },
  { name: "Brick Exception", hex: "#A86360", use: "Anomalies and review flags", color: "#A86360" },
];

export default function StyleGuidePage() {
  const [, setLocation] = useLocation();
  const { ambientMotion } = useMotion();
  return <main className="style-guide-page">
    <header className="style-guide-header"><Brand onClick={() => setLocation("/")} /><div className="flex items-center gap-2"><ThemeToggle /><button onClick={() => setLocation("/")} className="style-guide-back"><ArrowLeft className="h-4 w-4" />Public site</button></div></header>
    <section className="style-guide-intro"><div><p className="data-label text-primary">AeroIndex India / presentation system</p><h1>Institutional airspace,<br/><span>made legible.</span></h1><p>A compact visual reference for the professional palette, typographic hierarchy, and operational interface components used throughout the demonstration.</p></div><div className="style-guide-spec"><span>DESIGN SYSTEM</span><strong>AIX · VS-01</strong><small>Dark analytical default · Executive Light alternate</small></div></section>
    <section className="style-guide-section"><div className="style-guide-section-head"><div><p className="data-label">01 / Palette</p><h2>Professional institutional colors</h2></div><p>Color carries a defined analytical meaning; saturation is kept low for presentation and data clarity.</p></div><div className="swatch-grid">{colors.map((item) => <article className="swatch-card" key={item.name}><span style={{ background: item.color }} /><div><strong>{item.name}</strong><code>{item.hex}</code><p>{item.use}</p></div></article>)}</div></section>
    <section className="style-guide-section style-guide-columns"><div><div className="style-guide-section-head"><div><p className="data-label">02 / Type</p><h2>Clear hierarchy, calm density</h2></div></div><div className="type-samples"><p className="type-overline">Space Grotesk / 700 / 11px tracked</p><p className="type-display">National Signal<br/>Desk</p><p className="type-body">Space Grotesk supports information-rich route, source, and status content. Sora creates measured authority for major analytical states and numerical hierarchy.</p><div className="type-mono">AIX-2026.08.27 · DEL-BOM · 10:42:05 IST</div></div></div><div className="style-guide-side-note"><ShieldCheck className="h-5 w-5" /><strong>Typography rule</strong><p>Use Sora for conclusions and Space Grotesk for evidence. Never use display scale for routine UI labels.</p></div></section>
    <section className="style-guide-section"><div className="style-guide-section-head"><div><p className="data-label">03 / Components</p><h2>Engineered, not ornamental</h2></div><p>Clipped frame marks, disciplined tags and compact actions make the analytical workspace feel operational.</p></div><div className="component-showcase"><article className="style-component"><p className="data-label">Controls</p><div className="mt-4 flex flex-wrap gap-2"><button className="button-primary">Open analysis <ArrowRight className="h-4 w-4" /></button><button className="button-secondary">Reference view</button></div></article><article className="style-component"><p className="data-label">Analytical state</p><div className="mt-4 flex flex-wrap gap-2"><span className="status-success"><CheckCircle2 className="mr-1 h-3 w-3" />Validated</span><span className="status-warn">Reference</span><span className="status-danger"><CircleAlert className="mr-1 h-3 w-3" />Anomaly</span></div></article><article className="style-component"><p className="data-label">Instrument tile</p><div className="instrument-card mt-4"><div className="flex items-start justify-between"><div><p className="data-label">CPI compatibility</p><strong className="mt-1 block font-display text-2xl">92/100</strong></div><Database className="h-5 w-5 text-primary" /></div><p className="mt-3 text-xs text-muted-foreground">High reliability · current observation</p></div></article><article className="style-component"><p className="data-label">Theme context</p><div className="mt-4 rounded-lg border border-border bg-secondary/45 p-4"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Executive Light</span><ThemeToggle /></div><p className="mt-3 text-xs leading-5 text-muted-foreground">A calm, high-contrast alternate for executive reviews and light presentation environments.</p></div></article></div></section>
    <section className="style-guide-section accessibility-guide"><div className="style-guide-section-head"><div><p className="data-label">04 / Accessibility</p><h2>Motion remains under user control</h2></div><p>Ambient airspace motion supports atmosphere, never comprehension. The interface keeps the experience usable when animation is reduced.</p></div><div className="accessibility-showcase"><article className="accessibility-state"><span className={`accessibility-orbit ${ambientMotion ? "is-moving" : "is-still"}`}><i /><i /><i /></span><div><p className="data-label">Current state</p><strong>{ambientMotion ? "Ambient motion enabled" : "Reduced motion enabled"}</strong><p>{ambientMotion ? "Aircraft drift, cloud layers and route paths move at low amplitude." : "Aircraft, cloud layers and route paths remain still; interface feedback remains intact."}</p></div></article><article className="accessibility-state"><Keyboard className="h-5 w-5 text-primary" /><div><p className="data-label">Keyboard shortcut</p><strong>Toggle ambient motion with <kbd>M</kbd></strong><p>The shortcut is ignored while focus is in a text field, selector, or editable region.</p></div></article><article className="accessibility-state accessibility-live-control"><Accessibility className="h-5 w-5 text-primary" /><div><p className="data-label">Live control</p><strong>Demonstrate the setting</strong><p>Use the real persisted preference below; hover or focus for the contextual explanation.</p></div><AmbientMotionControl presentation /></article></div></section>
    <section className="style-guide-closing"><div><p className="data-label text-primary">AeroIndex India</p><h2>One evidence-led visual language.</h2></div><button onClick={() => setLocation("/login")} className="button-primary">Enter demonstration <ArrowRight className="h-4 w-4" /></button></section>
  </main>;
}
